controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.25
    wheel_radius: 0.033
    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: false  # <-- ВАЖНО: Отключаем публикацию TF здесь, чтобы не было конфликта с EKF
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    open_loop: false
    cmd_vel_timeout: 0.5
    use_stamped_vel: false

joint_broadcaster:
  ros__parameters:
    use_sim_time: false
