slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Имена фреймов (ДОЛЖНЫ СОВПАДАТЬ С URDF И НАШЕЙ НОДОЙ)
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    
    mode: mapping
    use_sim_time: false  # <-- КРИТИЧНО: должно быть false, как в launch-файле
    
    publish_tf: true
    transform_publish_period: 0.05
    transform_timeout: 0.5
    
    # Оптимизация для Raspberry Pi
    minimum_time_interval: 0.5
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_score_coarse: 0.55
    loop_match_minimum_score_fine: 0.45
    loop_search_maximum_distance: 5.0
    
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    do_scan_matching: true
    do_localization: false
